import Head from "next/head";
import { useInView } from "react-intersection-observer";
import ScrollWrapper from "./elements/ScrollWrapper";

import styles from "../styles/Home.module.css";

export default function Home() {
  const { ref, inView } = useInView({
    threshold: 0,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ScrollWrapper inView={inView}>
          <div ref={ref} className={styles.inviewblock}>
            <h2>
              Element is inside the viewport:{" "}
              <strong>{inView.toString()}</strong>
            </h2>
          </div>
        </ScrollWrapper>
      </main>
    </>
  );
}
